project:
  type: website

# Metadata stuff
author-meta: "Felipe Gonzalez"

website:
  title: "Felipe Gonzalez"
  description: "Felipe Gonzalez's personal website"
  repo-url: https://github.com/felipe3dfx/felipe-gonzalez.com
  favicon: img/favicon.ico
  repo-actions: [issue]
  reader-mode: true
  twitter-card:
    creator: "@felipezul"
    site: "@felipezul"
  navbar:
    right:
      - href: index.qmd
        text: About

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: true
