project:
  type: website
  output-dir: docs

# Metadata stuff
author-meta: "Felipe Gonzalez"

website:
  title: "Felipe Gonzalez"
  description: "Felipe Gonzalez's personal website"
  repo-url: https://github.com/felipe3dfx/felipe-gonzalez.com
  repo-actions: [issue]
  reader-mode: true
  cookie-consent:
    type: express
    style: headline
    palette: dark
  twitter-card:
    creator: "@felipezul"
    site: "@felipezul"
  navbar:
    right:
      - href: index.qmd
        text: About

format:
  html:
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/**'
    theme: 
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: true



